In [7]:
import keras
import numpy as np
from model import train_model
from data_preprocess import get_data

### Load the data and train the model

In [8]:
# x_train, x_test, y_train, y_test = get_data('sudoku.csv')

# train_model(x_train, y_train)

### Loading pretrained model

In [9]:
model = keras.models.load_model('sudoku.model')

### Solving the puzzle

In [10]:
def norm(a):
    
    return (a/9)-.5

In [11]:
def denorm(a):
    
    return (a+.5)*9

In [12]:
def inference_sudoku(sample):
    
    '''
        This function solve the sudoku by filling blank positions one by one.
    '''
    
    feat = sample
    
    while(1):
    
        out = model.predict(feat.reshape((1,9,9,1)))  
        out = out.squeeze()

        pred = np.argmax(out, axis=1).reshape((9,9))+1 
        prob = np.around(np.max(out, axis=1).reshape((9,9)), 2) 
        
        feat = denorm(feat).reshape((9,9))
        mask = (feat==0)
     
        if(mask.sum()==0):
            break
            
        prob_new = prob*mask
    
        ind = np.argmax(prob_new)
        x, y = (ind//9), (ind%9)

        val = pred[x][y]
        feat[x][y] = val
        feat = norm(feat)
    
    return pred

In [13]:
def test_accuracy(feats, labels):
    
    correct = 0
    
    for i,feat in enumerate(feats):
        
        pred = inference_sudoku(feat)
        
        true = labels[i].reshape((9,9))+1
        
        if(abs(true - pred).sum()==0):
            correct += 1
        
    print(correct/feats.shape[0])

In [16]:
test_accuracy(x_test[:100], y_test[:100])

1.0


In [51]:
game = '080032001703080002500007030050001970600709008047200050020600009800090305300820010'

game = np.array([int(j) for j in game]).reshape((9,9,1))
game = norm(game)
game = inference_sudoku(game)

print('solved puzzle:\n')
print(game)

solved puzzle:

[[4 8 9 5 3 2 7 6 1]
 [7 1 3 4 8 6 5 9 2]
 [5 6 2 9 1 7 8 3 4]
 [2 5 8 3 4 1 9 7 6]
 [6 3 1 7 5 9 2 4 8]
 [9 4 7 2 6 8 1 5 3]
 [1 2 5 6 7 3 4 8 9]
 [8 7 6 1 9 4 3 2 5]
 [3 9 4 8 2 5 6 1 7]]


In [52]:
np.sum(game, axis=0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])